### ISSUE TITLE
Input files were not found

### ISSUE THREAD

**Issue by Mazimah** [gavinmdouglas/picrust2_manuscript#3]
Hey, im new to conda, picrust and cmd. I have recently installed the picrust and try the full picrust pipeline. However there is this files were not found error which I do not have anyone to refer to. I would be glad if you could help assist me

picrust2_pipeline.py -s rep_set.fna -i otu_table_no_singletons.biom -o picrust2_out_pipeline -p 1
Traceback (most recent call last):
  File "/Users/mac/miniconda3/envs/picrust2/bin/picrust2_pipeline.py", line 264, in <module>
    main()
  File "/Users/mac/miniconda3/envs/picrust2/bin/picrust2_pipeline.py", line 255, in main
    verbose=args.verbose)
  File "/Users/mac/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/pipeline.py", line 115, in full_pipeline
    check_files_exist(files2check)
  File "/Users/mac/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/util.py", line 404, in check_files_exist
    ", ".join(missing_files))
ValueError: These input files were not found: rep_set.fna, otu_table_no_singletons.biom

**Comment by gavinmdouglas** [comment]
Hey @Mazimah,

That error suggests that the two input files cannot be found - can you confirm that they are in the current working directory?


Cheers,

Gavin
